# Site settings
title: Aceler Chua
email: hi@aclr.co
description: "Aceler Chua is a multidisciplinary designer based in Manila, Philippines."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aclr.co" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000/"
paginate: 5
paginate_path: "/article/page:num"
exclude: ["node_modules", "Gruntfile.js", "package.json", "css/dev", "js/dev", "README.md", "CNAME"]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
      permalink: /article/:title.html