# Site settings
title: Aceler Chua
email: hi@aclr.co
description: "Personal website of Aceler Chua—a designer who focuses on producing problem-solving solutions in various creative ways."
pattern: "/assets/pattern/aclr@2x.png"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aclr.co" # On Github
# url: "http://127.0.0.1:4000" # On local
paginate: 5
paginate_path: "/article/page:num"
permalink: /article/:title/
exclude: ["node_modules", "bower_components", "Gruntfile.js", "package.json", "bower.json", "js/dev", "readme.md", "CNAME"]

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
